prog: main.o meilleur_score1.o
	gcc  main.o meilleur_score1.o -o prog -lSDL -g -lSDL_image -lSDL_ttf -lSDL_mixer
menu.o:meilleur_score1.c
	gcc -c meilleur_score1.c -g
main.o:main.c
	gcc -c main.c -g

